services:

  postgres:
    image: postgres:15
    container_name: insights_postgres
    environment:
      POSTGRES_DB: insightsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dewalt0070806@@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./deinsights-backendmo
    container_name: insights_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/insightsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./New_project_Dashboard
    container_name: insights_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
